### ISSUE TITLE
UTF-8 encoding issues on Heroku

### ISSUE THREAD

**Issue by diasks2** [diasks2/heroku-buildpack-mecab#1]
On my local machine the app outputs:
["今日", "は", "日曜日", "。", "明日", "は", "月曜日", "。"]

On Heroku the app outputs:
["\xE4\xBB", "\x8A日\xE3\x81", "\xAF\xE6", "\x97\xA5曜日。明\xE6\x97", "\xA5\xE3", "\x81\xAF月曜\xE6\x97", "\xA5\xE3", "\x80\x82"]

**Comment by jkatzer** [comment]
this is likely just an issue with the vendor binary and not the repo itself. recompiling mecab now with the flag --with-charset=utf-8

**Comment by jkatzer** [comment]
check the hip chat for a new file to put on s3 and give it a spin

**Comment by diasks2** [comment]
Thanks, that solved it! https://github.com/diasks2/heroku-buildpack-mecab/commit/af0abc122c508e9055c558b04b447d6a8fedd245
