### ISSUE TITLE
missing mecab copyright notice?

### ISSUE THREAD

**Issue by hanachin** [diasks2/heroku-buildpack-mecab#3]
[mecab 0.996](http://code.google.com/p/mecab/downloads/detail?name=mecab-0.996.tar.gz) COPYING

> MeCab is copyrighted free software by Taku Kudo taku@chasen.org and
> Nippon Telegraph and Telephone Corporation, and is released under
> any of the GPL (see the file GPL), the LGPL (see the file LGPL), or the
> BSD License (see the file BSD).

and the mecab BSD file says:

> Copyright (c) 2001-2008, Taku Kudo
> Copyright (c) 2004-2008, Nippon Telegraph and Telephone Corporation
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are
> permitted provided that the following conditions are met:
> - Redistributions of source code must retain the above
>   copyright notice, this list of conditions and the
>   following disclaimer.
> - Redistributions in binary form must reproduce the above
>   copyright notice, this list of conditions and the
>   following disclaimer in the documentation and/or other
>   materials provided with the distribution.
> - Neither the name of the Nippon Telegraph and Telegraph Corporation
>   nor the names of its contributors may be used to endorse or
>   promote products derived from this software without specific
>   prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
> WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
> PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
> ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
> LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
> INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
> TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
> ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

this buildpack contains compiled mecab binary in [`mecab/libmecab-heroku.tar.gz`](https://github.com/diasks2/heroku-buildpack-mecab/blob/fbecc3eb44c2ba32073598f4ed852c9acfd0fa21/mecab/libmecab-heroku.tar.gz).
so you need to put the mecab's BSD license file somewhere in this buildpack.

**Comment by diasks2** [comment]
Thank you. I added the above to the buildpack README https://github.com/diasks2/heroku-buildpack-mecab/commit/415a9aebd9b7cd8020fa2eee0ae3c4a4bcf1df57

**Comment by hanachin** [comment]
Thank you <3
